### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by angelf** [studio-b12/monopod#2]
Hi,

With node v.6.3.0 and npm 3.10.3 on OS X we are getting a maximum call stack size exceed error. Project layout after "monopod bootstrap" is just

```
.
./node_modules
./node_modules/@monopod-debug
./packages
./packages/a
./packages/a/node_modules
./packages/a/package.json
./packages/b
./packages/b/node_modules
./packages/b/package.json
```

And both a & b are "pristine" packages (right out of npm init). 

The call stack is due to recursive calling flatNameFromTree...

```
Trace
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:479:12)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/deps.js:485:14)
```

**Comment by ghost** [comment]
Hello angelf,

thanks for your interest! Monopod is actually still in "work in progress", but because of insufficient resources right now, we won't be able to develop it further until probably mid august.

Because of the same reason, please feel free to send pull requests if you can find out a solution. If not, I'll come back to this as soon as I finish my current project!

Regards,
bck
